"use client";
import { useState } from "react";
import { Download, ExternalLink, Flame, LoaderCircle, Sparkles } from "lucide-react";
import JobQueue from "@/components/job-queue";

const ideas=["Create a heavyweight electrician tee for people who outwork everyone. Use power, current, and overtime themes.","Create a blue-collar dad hoodie about building a better life even when money is tight.","Create a minimal loyalty tee with a small front mark and a bold premium back print.","Create a dangerous collection design centered on discipline, focus, and refusing to quit."];
const labels=["Understanding Brand DNA","Writing product concept","Generating print artwork","Removing background","Saving to Design Library"];

export default function AiStudio(){
 const [prompt,setPrompt]=useState(ideas[0]); const [productType,setProductType]=useState('Heavyweight Tee'); const [loading,setLoading]=useState(false); const [result,setResult]=useState(null); const [error,setError]=useState(''); const [stages,setStages]=useState([]);
 async function generate(){setLoading(true);setError('');setResult(null);setStages(labels.map((label,i)=>({label,status:i===0?'active':'pending'})));let timer=setInterval(()=>setStages(current=>{const active=current.findIndex(x=>x.status==='active');if(active<0||active>=current.length-1)return current;return current.map((x,i)=>i===active?{...x,status:'done'}:i===active+1?{...x,status:'active'}:x)}),4500);try{const r=await fetch('/api/ai/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt,productType})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Generation failed.');setResult(d);setStages(labels.map(label=>({label,status:'done'})));window.dispatchEvent(new Event('brokie-design-created'));}catch(e){setError(e.message);setStages(current=>current.map(x=>x.status==='active'?{...x,status:'error'}:x))}finally{clearInterval(timer);setLoading(false)}}
 function download(){if(!result?.image?.dataUrl)return;const a=document.createElement('a');a.href=result.image.dataUrl;a.download=`${result.concept.concept_name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}.png`;a.click()}
 return <section className="panel" id="ai"><div className="panelHead"><div><span className="eyebrow">FOUNDRY</span><h2>Forge a product from one idea</h2></div><Flame className="orangeIcon"/></div>
 <div className="aiLiveLayout"><div className="aiControls"><label>Product type<select value={productType} onChange={e=>setProductType(e.target.value)}><option>Heavyweight Tee</option><option>Premium Hoodie</option><option>Oversized Tee</option><option>Embroidered Hat</option><option>Sticker</option></select></label><label>Describe what you want to forge<textarea value={prompt} onChange={e=>setPrompt(e.target.value)}/></label><div className="promptIdeas">{ideas.map(x=><button className="promptChip" type="button" key={x} onClick={()=>setPrompt(x)}>{x}</button>)}</div><button onClick={generate} disabled={loading||prompt.trim().length<10}>{loading?<LoaderCircle className="spin" size={17}/>:<Sparkles size={17}/>} {loading?'Forging product…':'Forge product concept'}</button><p className="aiCostNote">Every run is protected by admin login and recorded in the activity log.</p>{error&&<div className="managerNotice error">{error}</div>}</div>
 <div className="aiLiveOutput">{result?<><div className="generatedArtwork"><img src={result.image.dataUrl} alt={result.concept.concept_name}/></div><div className="generatedHeader"><div><small>{result.concept.collection_name}</small><h3>{result.concept.concept_name}</h3></div><span className={result.image.savedToSupabase?'savedPill':'previewPill'}>{result.image.savedToSupabase?'SAVED TO LIBRARY':'PREVIEW ONLY'}</span></div><blockquote>{result.concept.headline}</blockquote><div className="copyGrid"><article><small>PRODUCT TITLE</small><strong>{result.concept.product_title}</strong></article><article><small>RETAIL PRICE</small><strong>${Number(result.concept.retail_price).toFixed(2)}</strong></article></div><p className="generatedDescription">{result.concept.product_description}</p><div className="generatedTags">{result.concept.tags.map(t=><span key={t}>{t}</span>)}</div><div className="generatedActions"><button onClick={download}><Download size={16}/> Download PNG</button>{result.image.publicUrl&&<a href={result.image.publicUrl} target="_blank" rel="noreferrer">Public artwork URL <ExternalLink size={14}/></a>}</div></>:<div className="emptyOutput"><Flame size={34}/><strong>The next Brokie product starts here.</strong><span>Foundry creates the concept, artwork, product copy, pricing, tags, and a permanent Design Library record.</span></div>}</div></div>
 <JobQueue stages={stages} running={loading}/></section>
}
